#
# Copyright 2022-2025 Broadcom. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
version=2.0.2-build.9999

gemfireVersion=10.1.1
springSessionDataGemFireVersion=2.0.+
springDataGemFireVersion=2.0.+

spring-framework.version=6.1.+
spring-data-bom.version=2024.0.+
spring-boot.version=3.3.+
spring-session.version=3.3.+
spring-security.version=6.3.+

org.gradle.workers.max=3
org.gradle.parallel=true

docsGCSBucket=
docsGCSProject=

springTestGemfireDockerImage=gemfire/gemfire:10.1-jdk17

