#
# Copyright 2022-2025 Broadcom. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
version=2.0.0-build.9999

gemfireVersion=10.2.0
springSessionDataGemFireVersion=2.0.+
springDataGemFireVersion=2.0.+

spring-framework.version=7.0.1
spring-data-bom.version=2025.1.0
spring-boot.version=4.0.0
spring-session.version=4.0.0
spring-security.version=7.0.0

org.gradle.workers.max=3
org.gradle.parallel=true

docsGCSBucket=
docsGCSProject=

springTestGemfireDockerImage=gemfire/gemfire:10.2-jdk17


