#
# Copyright $originalComment.match(" (\d+)", 1, "-", $today.year)2026 Broadcom. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
version=1.0.4-build.9999

gemfireVersion=[10.1,10.2]
springSessionDataGemFireVersion=[2.0,3.0]
springDataGemFireVersion=[2.0,3.0]

additionalMavenRepoURLs=''

spring-framework.version=6.1.27
spring-data-bom.version=2024.0.13
spring-boot.version=3.3.13
spring-session.version=3.3.7
spring-security.version=6.3.15

org.gradle.workers.max=3
org.gradle.parallel=true

docsGCSBucket=
docsGCSProject=

springTestGemfireDockerImage=gemfire/gemfire:10.1-jdk17

