[versions]
antlrVersion = "2.7.7"
aspectjToolsVersion = "1.9.25.1"
awaitilityVersion = "4.2.2"
benManesVersions = "0.54.0"
findbugsVersion = "3.0.2"
gemFireTestContainersVersion = "2.3.3"
gemfireVersion = "10.2.7"
jettyEe8Version = "12.0.37"
kotlinGradlePluginVersion = "2.1.21"
littlerobotsVersionCatalogUpdate = "1.1.0"
lombokPlugin = "8.6"
mockitoCoreVersion = { strictly = "5.14.2" }
multithreadedtcVersion = "1.01"
springBootVersion = "3.5.16"
springDataBomVersion = "2025.0.13"
springDataGemFireVersion = "1.0.0"
springFrameworkVersion = "6.2.19"
springSecurityVersion = "6.5.11"
springSessionBomVersion = "3.5.7"
springSessionDataGemFireVersion = "1.0.0"
springShellVersion = "1.2.0.RELEASE"

[libraries]
antlr = { module = "antlr:antlr", version.ref = "antlrVersion" }
aspectj-tools = { module = "org.aspectj:aspectjtools", version.ref = "aspectjToolsVersion" }
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitilityVersion" }
findbugs-jsr305 = { module = "com.google.code.findbugs:jsr305", version.ref = "findbugsVersion" }
gemfire-core = { module = "com.vmware.gemfire:gemfire-core", version.ref = "gemfireVersion" }
gemfire-cq = { module = "com.vmware.gemfire:gemfire-cq", version.ref = "gemfireVersion" }
gemfire-deployment-chained-classloader = { module = "com.vmware.gemfire:gemfire-deployment-chained-classloader", version.ref = "gemfireVersion" }
gemfire-gfsh = { module = "com.vmware.gemfire:gemfire-gfsh", version.ref = "gemfireVersion" }
gemfire-logging = { module = "com.vmware.gemfire:gemfire-logging", version.ref = "gemfireVersion" }
gemfire-membership = { module = "com.vmware.gemfire:gemfire-membership", version.ref = "gemfireVersion" }
gemfire-serialization = { module = "com.vmware.gemfire:gemfire-serialization", version.ref = "gemfireVersion" }
gemfire-tcp-server = { module = "com.vmware.gemfire:gemfire-tcp-server", version.ref = "gemfireVersion" }
gemfire-testcontainers = { module = "dev.gemfire:gemfire-testcontainers", version.ref = "gemFireTestContainersVersion" }
gemfire-wan = { module = "com.vmware.gemfire:gemfire-wan", version.ref = "gemfireVersion" }
gemfire-web = { module = "com.vmware.gemfire:gemfire-web", version.ref = "gemfireVersion" }
jetty-ee10-webapp = { module = "org.eclipse.jetty.ee10:jetty-ee10-webapp", version.ref = "jettyEe8Version" }
jetty-ee8-apache-jsp = { module = "org.eclipse.jetty.ee8:jetty-ee8-apache-jsp", version.ref = "jettyEe8Version" }
jetty-ee8-webapp = { module = "org.eclipse.jetty.ee8:jetty-ee8-webapp", version.ref = "jettyEe8Version" }
jetty-jndi = { module = "org.eclipse.jetty:jetty-jndi", version.ref = "jettyEe8Version" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinGradlePluginVersion" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCoreVersion" }
multithreadedtc = { module = "edu.umd.cs.mtc:multithreadedtc", version.ref = "multithreadedtcVersion" }
spring-boot-bom = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "springBootVersion" }
spring-data-bom = { module = "org.springframework.data:spring-data-bom", version.ref = "springDataBomVersion" }
spring-data-gemfire = { module = "com.vmware.gemfire:spring-data-3.5-gemfire-10.2", version.ref = "springDataGemFireVersion" }
spring-data-gemfire-test-framework = { module = "com.vmware.gemfire:spring-data-3.5-gemfire-test-framework-10.2", version.ref = "springDataGemFireVersion" }
spring-framework-bom = { module = "org.springframework:spring-framework-bom", version.ref = "springFrameworkVersion" }
spring-security-bom = { module = "org.springframework.security:spring-security-bom", version.ref = "springSecurityVersion" }
spring-session-bom = { module = "org.springframework.session:spring-session-bom", version.ref = "springSessionBomVersion" }
spring-session-gemfire = { module = "com.vmware.gemfire:spring-session-3.5-gemfire-10.2", version.ref = "springSessionDataGemFireVersion" }
spring-shell = { module = "org.springframework.shell:spring-shell", version.ref = "springShellVersion" }

[plugins]
ben-manes-versions = { id = "com.github.ben-manes.versions", version.ref = "benManesVersions" }
littlerobots-version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "littlerobotsVersionCatalogUpdate" }
lombok = { id = "io.freefair.lombok", version.ref = "lombokPlugin" }
