[versions]
aspectjToolsVersion = "1.9.25.1"
benManesVersions = "0.54.0"
findbugsVersion = "3.0.2"
gemFireTestContainersVersion = "3.0.0"
gemfireVersion = "10.4.0"
littlerobotsVersionCatalogUpdate = "1.1.0"
lombokVersion = "1.18.46"
mockitoCoreVersion = "5.23.0"
multithreadedtcVersion = "1.01"
springBootVersion = "4.1.0"
springDataBomVersion = "2026.0.0"
springDataGemFireVersion = "2.0.0"
springFrameworkVersion = "7.0.8"
springSecurityVersion = "7.1.0"
springSessionBomVersion = "4.1.0"
springSessionDataGemFireVersion = "2.0.0"
springShellVersion = "1.2.0.RELEASE"

[libraries]
aspectj-tools = { module = "org.aspectj:aspectjtools", version.ref = "aspectjToolsVersion" }
findbugs-jsr305 = { module = "com.google.code.findbugs:jsr305", version.ref = "findbugsVersion" }
gemfire-core = { module = "com.vmware.gemfire:gemfire-core", version.ref = "gemfireVersion" }
gemfire-cq = { module = "com.vmware.gemfire:gemfire-cq", version.ref = "gemfireVersion" }
gemfire-deployment-chained-classloader = { module = "com.vmware.gemfire:gemfire-deployment-chained-classloader", version.ref = "gemfireVersion" }
gemfire-gfsh = { module = "com.vmware.gemfire:gemfire-gfsh", version.ref = "gemfireVersion" }
gemfire-logging = { module = "com.vmware.gemfire:gemfire-logging", version.ref = "gemfireVersion" }
gemfire-serialization = { module = "com.vmware.gemfire:gemfire-serialization", version.ref = "gemfireVersion" }
gemfire-tcp-server = { module = "com.vmware.gemfire:gemfire-tcp-server", version.ref = "gemfireVersion" }
gemfire-testcontainers = { module = "dev.gemfire:gemfire-testcontainers", version.ref = "gemFireTestContainersVersion" }
gemfire-web = { module = "com.vmware.gemfire:gemfire-web", version.ref = "gemfireVersion" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombokVersion" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockitoCoreVersion" }
mockito-subclass = { module = "org.mockito:mockito-subclass", version.ref = "mockitoCoreVersion" }
multithreadedtc = { module = "edu.umd.cs.mtc:multithreadedtc", version.ref = "multithreadedtcVersion" }
spring-boot-bom = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "springBootVersion" }
spring-data-bom = { module = "org.springframework.data:spring-data-bom", version.ref = "springDataBomVersion" }
spring-data-gemfire = { module = "com.vmware.gemfire:spring-data-4.1-gemfire-10.4", version.ref = "springDataGemFireVersion" }
spring-data-gemfire-test-framework = { module = "com.vmware.gemfire:spring-data-4.1-gemfire-test-framework-10.4", version.ref = "springDataGemFireVersion" }
spring-framework-bom = { module = "org.springframework:spring-framework-bom", version.ref = "springFrameworkVersion" }
spring-security-bom = { module = "org.springframework.security:spring-security-bom", version.ref = "springSecurityVersion" }
spring-session-bom = { module = "org.springframework.session:spring-session-bom", version.ref = "springSessionBomVersion" }
spring-session-gemfire = { module = "com.vmware.gemfire:spring-session-4.1-gemfire-10.4", version.ref = "springSessionDataGemFireVersion" }
spring-shell = { module = "org.springframework.shell:spring-shell", version.ref = "springShellVersion" }

[plugins]
ben-manes-versions = { id = "com.github.ben-manes.versions", version.ref = "benManesVersions" }
littlerobots-version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "littlerobotsVersionCatalogUpdate" }
